//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelOfficer.PersonnelOfficerServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PersonnelOfficerServiceRef.IWCFService")]
    public interface IWCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/SaveEmployee", ReplyAction="http://tempuri.org/IWCFService/SaveEmployeeResponse")]
        PersonnelOfficer.PersonnelOfficerServiceRef.SaveEmployeeResponse SaveEmployee(PersonnelOfficer.PersonnelOfficerServiceRef.SaveEmployeeRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/SaveEmployee", ReplyAction="http://tempuri.org/IWCFService/SaveEmployeeResponse")]
        System.Threading.Tasks.Task<PersonnelOfficer.PersonnelOfficerServiceRef.SaveEmployeeResponse> SaveEmployeeAsync(PersonnelOfficer.PersonnelOfficerServiceRef.SaveEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/DeleteEmployee", ReplyAction="http://tempuri.org/IWCFService/DeleteEmployeeResponse")]
        bool DeleteEmployee(PersonalOfficerLibrary.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/DeleteEmployee", ReplyAction="http://tempuri.org/IWCFService/DeleteEmployeeResponse")]
        System.Threading.Tasks.Task<bool> DeleteEmployeeAsync(PersonalOfficerLibrary.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/SaveDepartment", ReplyAction="http://tempuri.org/IWCFService/SaveDepartmentResponse")]
        PersonnelOfficer.PersonnelOfficerServiceRef.SaveDepartmentResponse SaveDepartment(PersonnelOfficer.PersonnelOfficerServiceRef.SaveDepartmentRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/SaveDepartment", ReplyAction="http://tempuri.org/IWCFService/SaveDepartmentResponse")]
        System.Threading.Tasks.Task<PersonnelOfficer.PersonnelOfficerServiceRef.SaveDepartmentResponse> SaveDepartmentAsync(PersonnelOfficer.PersonnelOfficerServiceRef.SaveDepartmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/DeleteDepartment", ReplyAction="http://tempuri.org/IWCFService/DeleteDepartmentResponse")]
        bool DeleteDepartment(PersonalOfficerLibrary.Department department);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/DeleteDepartment", ReplyAction="http://tempuri.org/IWCFService/DeleteDepartmentResponse")]
        System.Threading.Tasks.Task<bool> DeleteDepartmentAsync(PersonalOfficerLibrary.Department department);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/SavePosition", ReplyAction="http://tempuri.org/IWCFService/SavePositionResponse")]
        PersonnelOfficer.PersonnelOfficerServiceRef.SavePositionResponse SavePosition(PersonnelOfficer.PersonnelOfficerServiceRef.SavePositionRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/SavePosition", ReplyAction="http://tempuri.org/IWCFService/SavePositionResponse")]
        System.Threading.Tasks.Task<PersonnelOfficer.PersonnelOfficerServiceRef.SavePositionResponse> SavePositionAsync(PersonnelOfficer.PersonnelOfficerServiceRef.SavePositionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/DeletePosition", ReplyAction="http://tempuri.org/IWCFService/DeletePositionResponse")]
        bool DeletePosition(PersonalOfficerLibrary.Position position);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/DeletePosition", ReplyAction="http://tempuri.org/IWCFService/DeletePositionResponse")]
        System.Threading.Tasks.Task<bool> DeletePositionAsync(PersonalOfficerLibrary.Position position);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetEmployees", ReplyAction="http://tempuri.org/IWCFService/GetEmployeesResponse")]
        PersonalOfficerLibrary.Employee[] GetEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetEmployees", ReplyAction="http://tempuri.org/IWCFService/GetEmployeesResponse")]
        System.Threading.Tasks.Task<PersonalOfficerLibrary.Employee[]> GetEmployeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetDepartments", ReplyAction="http://tempuri.org/IWCFService/GetDepartmentsResponse")]
        PersonalOfficerLibrary.Department[] GetDepartments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetDepartments", ReplyAction="http://tempuri.org/IWCFService/GetDepartmentsResponse")]
        System.Threading.Tasks.Task<PersonalOfficerLibrary.Department[]> GetDepartmentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetPositions", ReplyAction="http://tempuri.org/IWCFService/GetPositionsResponse")]
        PersonalOfficerLibrary.Position[] GetPositions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetPositions", ReplyAction="http://tempuri.org/IWCFService/GetPositionsResponse")]
        System.Threading.Tasks.Task<PersonalOfficerLibrary.Position[]> GetPositionsAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveEmployee", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public PersonalOfficerLibrary.Employee employee;
        
        public SaveEmployeeRequest() {
        }
        
        public SaveEmployeeRequest(PersonalOfficerLibrary.Employee employee) {
            this.employee = employee;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveEmployeeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SaveEmployeeResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int employeeId;
        
        public SaveEmployeeResponse() {
        }
        
        public SaveEmployeeResponse(bool SaveEmployeeResult, int employeeId) {
            this.SaveEmployeeResult = SaveEmployeeResult;
            this.employeeId = employeeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveDepartment", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveDepartmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public PersonalOfficerLibrary.Department department;
        
        public SaveDepartmentRequest() {
        }
        
        public SaveDepartmentRequest(PersonalOfficerLibrary.Department department) {
            this.department = department;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveDepartmentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveDepartmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SaveDepartmentResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int departmentId;
        
        public SaveDepartmentResponse() {
        }
        
        public SaveDepartmentResponse(bool SaveDepartmentResult, int departmentId) {
            this.SaveDepartmentResult = SaveDepartmentResult;
            this.departmentId = departmentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SavePosition", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SavePositionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public PersonalOfficerLibrary.Position position;
        
        public SavePositionRequest() {
        }
        
        public SavePositionRequest(PersonalOfficerLibrary.Position position) {
            this.position = position;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SavePositionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SavePositionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SavePositionResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int positionId;
        
        public SavePositionResponse() {
        }
        
        public SavePositionResponse(bool SavePositionResult, int positionId) {
            this.SavePositionResult = SavePositionResult;
            this.positionId = positionId;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFServiceChannel : PersonnelOfficer.PersonnelOfficerServiceRef.IWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFServiceClient : System.ServiceModel.ClientBase<PersonnelOfficer.PersonnelOfficerServiceRef.IWCFService>, PersonnelOfficer.PersonnelOfficerServiceRef.IWCFService {
        
        public WCFServiceClient() {
        }
        
        public WCFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PersonnelOfficer.PersonnelOfficerServiceRef.SaveEmployeeResponse PersonnelOfficer.PersonnelOfficerServiceRef.IWCFService.SaveEmployee(PersonnelOfficer.PersonnelOfficerServiceRef.SaveEmployeeRequest request) {
            return base.Channel.SaveEmployee(request);
        }
        
        public bool SaveEmployee(PersonalOfficerLibrary.Employee employee, out int employeeId) {
            PersonnelOfficer.PersonnelOfficerServiceRef.SaveEmployeeRequest inValue = new PersonnelOfficer.PersonnelOfficerServiceRef.SaveEmployeeRequest();
            inValue.employee = employee;
            PersonnelOfficer.PersonnelOfficerServiceRef.SaveEmployeeResponse retVal = ((PersonnelOfficer.PersonnelOfficerServiceRef.IWCFService)(this)).SaveEmployee(inValue);
            employeeId = retVal.employeeId;
            return retVal.SaveEmployeeResult;
        }
        
        public System.Threading.Tasks.Task<PersonnelOfficer.PersonnelOfficerServiceRef.SaveEmployeeResponse> SaveEmployeeAsync(PersonnelOfficer.PersonnelOfficerServiceRef.SaveEmployeeRequest request) {
            return base.Channel.SaveEmployeeAsync(request);
        }
        
        public bool DeleteEmployee(PersonalOfficerLibrary.Employee employee) {
            return base.Channel.DeleteEmployee(employee);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteEmployeeAsync(PersonalOfficerLibrary.Employee employee) {
            return base.Channel.DeleteEmployeeAsync(employee);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PersonnelOfficer.PersonnelOfficerServiceRef.SaveDepartmentResponse PersonnelOfficer.PersonnelOfficerServiceRef.IWCFService.SaveDepartment(PersonnelOfficer.PersonnelOfficerServiceRef.SaveDepartmentRequest request) {
            return base.Channel.SaveDepartment(request);
        }
        
        public bool SaveDepartment(PersonalOfficerLibrary.Department department, out int departmentId) {
            PersonnelOfficer.PersonnelOfficerServiceRef.SaveDepartmentRequest inValue = new PersonnelOfficer.PersonnelOfficerServiceRef.SaveDepartmentRequest();
            inValue.department = department;
            PersonnelOfficer.PersonnelOfficerServiceRef.SaveDepartmentResponse retVal = ((PersonnelOfficer.PersonnelOfficerServiceRef.IWCFService)(this)).SaveDepartment(inValue);
            departmentId = retVal.departmentId;
            return retVal.SaveDepartmentResult;
        }
        
        public System.Threading.Tasks.Task<PersonnelOfficer.PersonnelOfficerServiceRef.SaveDepartmentResponse> SaveDepartmentAsync(PersonnelOfficer.PersonnelOfficerServiceRef.SaveDepartmentRequest request) {
            return base.Channel.SaveDepartmentAsync(request);
        }
        
        public bool DeleteDepartment(PersonalOfficerLibrary.Department department) {
            return base.Channel.DeleteDepartment(department);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteDepartmentAsync(PersonalOfficerLibrary.Department department) {
            return base.Channel.DeleteDepartmentAsync(department);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PersonnelOfficer.PersonnelOfficerServiceRef.SavePositionResponse PersonnelOfficer.PersonnelOfficerServiceRef.IWCFService.SavePosition(PersonnelOfficer.PersonnelOfficerServiceRef.SavePositionRequest request) {
            return base.Channel.SavePosition(request);
        }
        
        public bool SavePosition(PersonalOfficerLibrary.Position position, out int positionId) {
            PersonnelOfficer.PersonnelOfficerServiceRef.SavePositionRequest inValue = new PersonnelOfficer.PersonnelOfficerServiceRef.SavePositionRequest();
            inValue.position = position;
            PersonnelOfficer.PersonnelOfficerServiceRef.SavePositionResponse retVal = ((PersonnelOfficer.PersonnelOfficerServiceRef.IWCFService)(this)).SavePosition(inValue);
            positionId = retVal.positionId;
            return retVal.SavePositionResult;
        }
        
        public System.Threading.Tasks.Task<PersonnelOfficer.PersonnelOfficerServiceRef.SavePositionResponse> SavePositionAsync(PersonnelOfficer.PersonnelOfficerServiceRef.SavePositionRequest request) {
            return base.Channel.SavePositionAsync(request);
        }
        
        public bool DeletePosition(PersonalOfficerLibrary.Position position) {
            return base.Channel.DeletePosition(position);
        }
        
        public System.Threading.Tasks.Task<bool> DeletePositionAsync(PersonalOfficerLibrary.Position position) {
            return base.Channel.DeletePositionAsync(position);
        }
        
        public PersonalOfficerLibrary.Employee[] GetEmployees() {
            return base.Channel.GetEmployees();
        }
        
        public System.Threading.Tasks.Task<PersonalOfficerLibrary.Employee[]> GetEmployeesAsync() {
            return base.Channel.GetEmployeesAsync();
        }
        
        public PersonalOfficerLibrary.Department[] GetDepartments() {
            return base.Channel.GetDepartments();
        }
        
        public System.Threading.Tasks.Task<PersonalOfficerLibrary.Department[]> GetDepartmentsAsync() {
            return base.Channel.GetDepartmentsAsync();
        }
        
        public PersonalOfficerLibrary.Position[] GetPositions() {
            return base.Channel.GetPositions();
        }
        
        public System.Threading.Tasks.Task<PersonalOfficerLibrary.Position[]> GetPositionsAsync() {
            return base.Channel.GetPositionsAsync();
        }
    }
}
